apiVersion: v1
kind: Service
metadata:
    name: fleetman-webapp

spec:
    # This defines which pods are going to be represented by this Service
    # The service beconme a network endpoint for either other services
    # os maybe external users to connect to (e.g. Browser)
    selector:
        app: webapp

    ports:
        - name: http
          port: 80
          nodePort: 30080

    # We can use NodePort or ClusterIP;
    # NodePort -> make the service available to outside
    # ClusterIP -> makes a connection private, just between the microservices
    type: NodePort

